SELECT USER
FROM DUAL;
--==> SCOTT

SELECT *
FROM TAB;

--○ TBL_NEWBOARD 테이블 생성 (게시판 전용 테이블 생성)
CREATE TABLE TBL_NEWBOARD
( NUM       NUMBER(9)               NOT NULL   
, NAME      VARCHAR2(30)            NOT NULL
, PWD       VARCHAR2(20)            NOT NULL
, EMAIL     VARCHAR2(50)
, SUBJECT   VARCHAR2(100)           NOT NULL
, CONTENT   VARCHAR2(4000)          NOT NULL
, IPADDR    VARCHAR2(20)
, HITCOUNT  NUMBER DEFAULT 0        NOT NULL
, CREATED   DATE DEFAULT SYSDATE    NOT NULL
, CONSTRAINT NEWBOARD_NUM_PK PRIMARY KEY(NUM)
);
--==> Table TBL_NEWBOARD이(가) 생성되었습니다.

--○ 게시물 번호의 최대값을 얻어내는 쿼리문 구성
SELECT NVL(MAX(NUM),0) AS MAXNUM
FROM TBL_NEWBOARD;

--> 한 줄 구성
SELECT NVL(MAX(NUM),0) AS MAXNUM FROM TBL_NEWBOARD
;

--○ 게시물 작성 쿼리문 구성
INSERT INTO TBL_NEWBOARD(NUM, NAME, PWD, EMAIL, SUBJECT, CONTENT, IPADDR, HITCOUNT, CREATED)
VALUES(1, '한혜림', '1234', 'rim@test.com', '게시판 테스트', '게시판 작성중입니다.', '211.238.142.161', 0, SYSDATE);

--> 한 줄 구성
INSERT INTO TBL_NEWBOARD(NUM, NAME, PWD, EMAIL, SUBJECT, CONTENT, IPADDR, HITCOUNT, CREATED) VALUES(1, '한혜림', '1234', 'rim@test.com', '게시판 테스트', '게시판 작성중입니다.', '211.238.142.161', 0, SYSDATE)
;


--○ DB 레코드의 갯수를 가져오는 쿼리문 구성
SELECT COUNT(*) AS COUNT
FROM TBL_NEWBOARD;

--> 한 줄 구성
SELECT COUNT(*) AS COUNT FROM TBL_NEWBOARD
;


--○ 특정 영역의(시작번호 ~ 끝번호) 게시물의 목록을 읽어오는 쿼리문 구성
SELECT NUM, NAME, SUBJECT, HITCOUNT, CREATED
FROM 
(
    SELECT ROWNUM RNUM, DATA.*
    FROM
    (
        SELECT NUM, NAME, SUBJECT, HITCOUNT, TO_CHAR(CREATED, 'YYYY-MM-DD') AS CREATED
        FROM TBL_NEWBOARD
        ORDER BY NUM DESC
    )DATA
)
WHERE RNUM >= 1 AND RNUM <= 10;

--> 한 줄 구성
SELECT NUM, NAME, SUBJECT, HITCOUNT, CREATED FROM (SELECT ROWNUM RNUM, DATA.* FROM (SELECT NUM, NAME, SUBJECT, HITCOUNT, TO_CHAR(CREATED, 'YYYY-MM-DD') AS CREATED FROM TBL_NEWBOARD ORDER BY NUM DESC)DATA ) WHERE RNUM >= 1 AND RNUM <= 10
;


--○ 특정 게시물 조회에 따른 조회 횟수 증가 쿼리문 구성
UPDATE TBL_NEWBOARD
SET HITCOUNT = HITCOUNT + 1
WHERE NUM=1;

--> 한 줄 구성
UPDATE TBL_NEWBOARD SET HITCOUNT = HITCOUNT + 1 WHERE NUM=1
;


--○ 특정 게시물의 내용을 읽어오는 쿼리문 구성
SELECT NUM, NAME, PWD, EMAIL, SUBJECT, CONTENT, IPADDR, HITCOUNT, CREATED
FROM TBL_NEWBOARD
WHERE NUM=1;

--> 한 줄 구성
SELECT NUM, NAME, PWD, EMAIL, SUBJECT, CONTENT, IPADDR, HITCOUNT, CREATED FROM TBL_NEWBOARD WHERE NUM=1
;


--○ 특정 게시물을 삭제하는 쿼리문 구성
DELETE
FROM TBL_NEWBOARD
WHERE NUM=1;

--> 한 줄 구성
DELETE FROM TBL_NEWBOARD WHERE NUM=1
;


--○ 특정 게시물을 수정하는 쿼리문 구성 (→ Article.jsp 페이지 내에서 처리)
UPDATE TBL_NEWBOARD
SET NAME=?, PWD=?, EMAIL=?, SUBJECT=?, CONTENT=?
WHERE NUM=1;

--> 한 줄 구성
UPDATE TBL_NEWBOARD SET NAME=?, PWD=?, EMAIL=?, SUBJECT=?, CONTENT=? WHERE NUM=1
;


--○ 게시물 다음 번호 읽어오는 쿼리문 구성
SELECT NVL(MIN(NUM),-1) AS NEXTNUM
FROM TBL_NEWBOARD
WHERE NUM > 현재게시물번호;

--> 한 줄 구성
SELECT NVL(MIN(NUM),-1) AS NEXTNUM FROM TBL_NEWBOARD WHERE NUM > 현재게시물번호
;

--○ 게시물 이전 번호 읽어오는 쿼리문 구성
SELECT NVL(MAX(NUM),-1) AS BEFORENUM
FROM TBL_NEWBOARD
WHERE NUM < 현재게시물번호;


--> 한 줄 구성
SELECT NVL(MAX(NUM),-1) AS BEFORENUM FROM TBL_NEWBOARD WHERE NUM < 현재게시물번호
;